base/urls.py
from django.urls import path, include
from . import views

urlpatterns = [    
    path('', views.home, name = 'home'),
    path('room/<str:pk>/', views.room, name= 'room'),


    path('browse-topics/', views.borwseTopics, name='browse-topics'),
    path('activities/', views.activities, name='activities'),
    
    
    path('create-room/', views.createroom, name = 'create-room'),
    path('update-room/<str:pk>', views.updateroom, name = 'update-room'),
    path('delete-room/<str:pk>', views.deleteroom, name = 'delete-room'),
    
    
    path('delete-message/<str:pk>/', views.deleteMessage, name='delete-message')
]

base/models.py
from django.db.models.deletion import CASCADE, SET_NULL
from django.db import models
# from django.contrib.auth.models import User
# from django.contrib.auth.models import AbstractUser


# Create your models here.
# class User(AbstractUser):
#     name = models.CharField(max_length=50, null=True)
#     email = models.EmailField(unique=True, null=True)
#     bio = models.TextField(null=True)
#     avatar = models.ImageField(null=True, default="avatar.svg")

#     # USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = []
from user.models import User


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host         = models.ForeignKey(User, on_delete=SET_NULL, null=True) # ForeignKEy da host o'zgaruvchining qiymati User modelidan olinadi. Ya'ni, host User modelidagi foydalanuvchilarning biri
    participants = models.ManyToManyField(User, related_name='participants', null=True)
    topic        = models.ForeignKey(Topic, on_delete=SET_NULL, null=True) #on_delete=SET_NULL bu qiymatda agar parent class (Topic) ochib ketsa ham topic ozgaruvchi qiymati saqlanib qoladi
    name         = models.CharField(max_length=200)
    description  = models.TextField(null=True, blank=True)
    updated      = models.DateTimeField(auto_now=True) #har safar yangilab turadi
    created      = models.DateTimeField(auto_now_add=True) # +=_add faqat yaratilgandagi vaqt
    class Meta:
        ordering = ['-updated', '-created'] #update va created boyicha ordering qiladi yani eng oxirgo yangilangan submodel birinchi bolib turadi aga - siz yozilsa eng oxiri boladi


    def __str__(self) -> str:
        return self.name


class Message(models.Model):
    user    = models.ForeignKey(User, on_delete=CASCADE)
    room    = models.ForeignKey(Room, related_name='comment', on_delete=CASCADE) #agar qiymat cascade bo'lsa parent clas (Room) ma'lumotlari ochirilsa room o'zgaruvchi saqlagan qiymat ham o'chadi 
    body    = models.TextField()
    updated = models.DateTimeField(auto_now=True) #har safar yangilab turadi
    created = models.DateTimeField(auto_now_add=True) # +=_add faqat yaratilgandagi vaqt

    
    class Meta:
        ordering = ['-updated', '-created']
    

    def __str__(self):
        return self.body[:50]

    

base/forms.py
from django.forms import ModelForm
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from .models import Room, User


class RoomForm(ModelForm):
    class Meta:
        model   = Room
        fields  =  "__all__" #['name', 'topic'] #agar __all__ bolsa hamma Room fieldlari olinadi
        exclude = ['host', 'participants']



# class UserForm(ModelForm):
#     class Meta:
#         model = User
#         fields = ['avatar', 'name', 'username', 'username', 'email', 'bio']



# class MyUserCreationForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['name', 'username', 'email', 'password1', 'password2']

base/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Room, Topic, Message
from .forms import RoomForm


# Create your views here.
from django.http import HttpResponse

# rooms = [
#     {'id': 1, 'name': 'Muqumiy tadbiri'},
#     {'id': 2, 'name': 'Halqaro Stipendiyalar'},
#     {'id': 3, 'name': 'Menejment va Korparatsiya boshqaruvi'},
# ]

def home(request):
    q = request.GET.get('i') if request.GET.get('i') != None else '' # ?i parametr qiymatlarini oladi
    # rooms = Room.objects.filter(topic__name__icontains=q name__icontains=q)
    # (up) agar bunday bolsa hamma filtrdan o'tishi kerak, bizga esa faqat bitta filtrdan otsa kifoya, search bar uchun 
    # (up) biz Room dagi topic attributidagi Topic modelidagi name attributiga murojaat qilishimiz uchun __ (2ta _) qoyamiz
    # (up) icontains = q degani topic__name__ da q bo'lsa o'shani chiqaradi
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |       #dastur hech bolmasa bitta filtrdan o'tishi kerak
        Q(name__icontains=q) |              #shuning uchun mantiqiy amallar uchun Q modeli import qilindi
        Q(host__username__icontains=q) |    # | - or, & - end
        Q(description__icontains=q)
    )
    room_count = rooms.count()
    topics = Topic.objects.all()[:5]
    comments = Message.objects.filter(
        Q(room__topic__name__icontains=q)
    )
    index = {
        'rooms': rooms,
        'topics': topics, 
        'room_count': room_count,
        'comments': comments,
    }
    return render(request, 'base/home.html', index) #HttpResponse('This is home')


def room(request, pk):
    room = Room.objects.get(id=pk) #har bir sub model o'zining id siga ega bo'ladi, va ushbu id bilan aynan shu sub modelga murojaat qilinadi
    # for i in Room.objects.all():
    #     if int(pk) == i['id']:
    #         room  = i
    comments = room.comment.all()#.order_by('-created') (edited 19/03/22 check Model.Message.Meta) #(look model) related_name=comment (by default <Class name>_set: message_set) room objectining child objectini chaqiradi Room modeli uchun Comment modeli child hisoblanadi (models.py/Room ga qaralsin)
    participants = room.participants.all().order_by('username')
    if request.method == 'POST':
        Message.objects.create(#    # maybe .update(), .all(), .delete()
            user = request.user,
            room = room,
            body = request.POST.get('body'),
        )
        room.participants.add(request.user) #maybe .remove()
        return redirect('room', pk=room.id)
        
    contex = {'room': room, 'comments': comments, 'participants': participants}
    return render(request, 'base/room.html', contex) #HttpResponse('This is room')




@login_required(login_url='login') # @login_required -- login filter
def createroom(request):
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == "POST":
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name) #name=topic_name shu object bolsa create qiladi va created=True boladi yoki aksi
        Room.objects.create(
            name = request.POST.get('name'), # 'name' ni RoomForm bergan
            description = request.POST.get('description'), # 'description' ni RoomForm bergan
            topic = topic,
            host = request.user,
        )

        # form = RoomForm(request.POST)
        # if form.is_valid():
        #     room = form.save(commit=False)
        #     room.host = request.user
        #     room.save
        return redirect('/') #'/' or by name 'home'
    context = {'form': form, 'topics': topics, 'text':'Create'}
    return render(request, 'base/form_room.html', context)


@login_required(login_url='login')
def updateroom(request, pk):
    room = Room.objects.get(id=pk)
    topics = Topic.objects.all()
    if request.user != room.host:
        return HttpResponse('You are not allowet to edit')
    form = RoomForm(instance=room) #room ni update qiladi
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.topic = topic
        room.name = request.POST.get('name')
        room.description = request.POST.get('description')
        # form = RoomForm(request.POST, instance=room)
        # if form.is_valid():
            # form.save
        room.save()
        return redirect('/')
    context = {'form': form,'room': room, 'topics': topics, 'text': 'Update'}
    return render(request, 'base/form_room.html', context)


@login_required(login_url='login')
def deleteroom(request, pk):
    room    = Room.objects.get(id=pk)
    if request.user != room.host:
        return HttpResponse('You are not allowet to delete')
    if request.method == 'POST':
        room.delete()
        return redirect('/')
    context = {'obj': room}
    return render(request, 'base/delete.html', context)



@login_required(login_url='login')
def deleteMessage(request, pk):
    message = Message.objects.get(id=pk)
    if request.user != message.user:
        return HttpResponse('You are not allowed to delete')
    if request.method == 'POST':
        message.delete()
        return redirect('/')
    context = {'obj': message}
    return render(request, 'base/delete.html', context)


def borwseTopics(request):
    q = request.GET.get('i') if request.GET.get('i') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    
    context = {'topics': topics}
    return render(request, 'base/topics.html', context)


def activities(request):
    comments = Message.objects.all()
    
    context = {'comments': comments}
    return render(request, 'base/activity.html', context)

base/templates/base/activity.html
{%extends 'main.html'%}

{% block content %}
  <main class="layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{{request.META.HTTP_REFERER}}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
              </svg>
            </a>
            <h3>Recent Activities</h3>
          </div>
        </div>

        <div class="activities-page layout__body">
          {% for comment in comments %}
          <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
              <a href="{% url 'user-profile' comment.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                  <img src="{{ comment.user.avatar.url }}" />
                </div>
                <p>
                  @{{comment.user.username}}
                  <span>{{ comment.created | timesince }} ago</span>
                </p>
              </a>
              {% if request.user == comment.user %}
              <div class="roomListRoom__actions">
                <a href="{% url 'delete-message' comment.id %}">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                      d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                  </svg>
                </a>
              </div>
              {% endif %}
            </div>
            
            <div class="activities__boxContent">
              <p>replied to post “<a href="{% url 'room' comment.room.id %}">{{ comment.room }}</a>”</p>
              <div class="activities__boxRoomContent">
                {{ comment.body }}
              </div>
            </div>
          </div>
    {% endfor %}
        </div>
      </div>
    </div>
  </main>

{% endblock %}

base/templates/base/activity_component.html
<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>
    {% for comment in comments %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'user-profile' comment.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small">
            <img src="{{comment.user.avatar.url}}" />
          </div>
          <p>
            @{{comment.user.username}}
            <span>{{ comment.created | timesince }} ago</span>
          </p>
        </a>
        {% if request.user == comment.user %}
        <div class="roomListRoom__actions">
          <a href="{% url 'delete-message' comment.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
        </div>
        {% endif %}
      </div>
      
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'room' comment.room.id %}">{{ comment.room }}</a>”</p>
        <div class="activities__boxRoomContent">
          {{ comment.body }}
        </div>
      </div>
    </div>
    {% endfor %}
</div>





<!-- <h3>Recent Activity</h3>
<hr>
{% for comment in comments %}

    <div>
        <small> <a href="{% url 'user-profile' comment.user.id %}">@{{comment.user}}</a> {{comment.created | timesince}} ago </small>
        <small> replied to {{comment.room}} </small>

        <p> {{comment}} </p>
        {% if request.user == comment.user %} <a href="{% url 'delete-message' comment.id %}">Delete</a> {% endif %}
        <hr>
    </div>

{% endfor %} -->

base/templates/base/create-room.html
{% extends 'home.html' %}

{% block content %}
 
  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="index.html">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create Study Room</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="#">
            <div class="form__group">
              <label for="room_name">Room Name</label>
              <input id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" />
            </div>

            <div class="form__group">
              <label for="room_topic">Topic</label>
              <input required type="text" name="topic" id="room_topic" list="topic-list" />
              <datalist id="topic-list">
                <select id="room_topic">
                  <option value="">Select your topic</option>
                  <option value="Python">Python</option>
                  <option value="Django">Django</option>
                </select>
              </datalist>

            </div>


            <div class="form__group">
              <label for="room_about">About</label>
              <textarea name="room_about" id="room_about" placeholder="Write about your study group..."></textarea>
            </div>
            <div class="form__action">
              <a class="btn btn--dark" href="index.html">Cancel</a>
              <button class="btn btn--main" type="submit">Create Room</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{request.META.HTTP_REFERER}}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

base/templates/base/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
      <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{{room.host.avatar.url}}" />
        </div>
        <span>@{{room.host.username}}</span>
      </a>
      <div class="roomListRoom__actions">
        <span>{{room.created | timesince}} ago</span>
      </div>
    </div>
    <div class="roomListRoom__content">
      <a href="{% url 'room' room.id %}">{{room.name}}</a>
      <p>
        {{room.description}}
      </p>
    </div>
    <div class="roomListRoom__meta">
      <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>user-group</title>
          <path
            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
          ></path>
          <path
            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
          ></path>
          <path
            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
          ></path>
          <path
            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
          ></path>
        </svg>
        {{room.participants.all.count}} Joined
      </a>
      <p class="roomListRoom__topic">{{room.topic}}</p>
    </div>
</div>

{% endfor %}








    <!-- {% for room in rooms %}
        {% if request.user == room.host %}
            <a href="{% url 'update-room' room.id %}"> Edit </a>
            <a href="{% url 'delete-room' room.id %}">  Delete </a>
        {% endif %}
            <a href="{% url 'user-profile' room.host.id %}">@{{ room.host.username }}</a>
        <h3>
            {{ room.id }} -- <a href="{% url 'room' room.id %}">{{room.name}}</a>
        </h3>
        <small>{{ room.topic.name }}</small>
        <hr>
    {% endfor %}-->

base/templates/base/form_room.html
{% extends 'main.html' %}

{% block content %}
 
  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{% url 'home' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Create/Update Study Room</h3>
          </div>
        </div>
        <div class="layout__body">
          <form class="form" action="" method="POST">
            {% csrf_token %}
            
            <div class="form__group">
              <label for="room_topic">Topic Name</label>
              <input required type="text" value="{{ room.topic }}" name="topic" list="topic-list"/> <!--required bosa topic tanlash shart. list="" topiclar --> 
              <datalist id="topic-list"> <!--yozgan payt -->
                <select id="room_topic">
                  {% for topic in topics %}
                    <option value="{{topic.name}}">{{ topic.name }}</option>
                  {% endfor %}
                </select>
              </datalist>
            </div>
            
            <div class="form__group">
              <label for="room_name">Room Name</label>
              {{form.name}}
              <!-- <input id="room_name" name="room_name" type="text" placeholder="E.g. Mastering Python + Django" /> -->
            </div>

            <div class="form__group">
              <label for="room_description">Description</label>
              {{form.description}}
              <!-- <textarea name="room_about" id="room_about" placeholder="Write about your study group..."></textarea> -->
            </div>

            
            <div class="form__action">
              <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
              <button class="btn btn--main" type="submit">{{text}} Room</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

base/templates/base/home.html
{%extends 'main.html'%}

{% block content %}

  <main class="layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {% include 'base/topics_component.html' %}
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="mobile-menu">
          <form action="{% url 'home' %}" method="GET" class="header__search">
            <label>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>search</title>
                <path
                  d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                ></path>
              </svg>
              <input name="i" placeholder="Search for posts" />
            </label>
          </form>
          <div class="mobile-menuItems">
            <a class="btn btn--main btn--pill" href="{% url 'browse-topics' %}">Browse Topics</a>
            <a class="btn btn--main btn--pill" href="{% url 'activities' %}">Recent Activities</a>
          </div>
        </div>
        <div class="roomList__header">
          <div>
            <h2>Study Room</h2>
            <p>{{room_count}} Rooms available</p>
          </div>
          <a class="btn btn--main" href="{% url 'create-room' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>add</title>
              <path
                d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
              ></path>
            </svg>
            Create Room
          </a>
        </div>
        {% include 'base/feed_component.html' %}
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
        <div>{% include 'base/activity_component.html' %}</div>
      <!-- Activities End -->
    </div>
  </main>

{% endblock %}

base/templates/base/topics.html
{%extends 'main.html'%}

{% block content %}
  <main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href="{{request.META.HTTP_REFERER}}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
              </svg>
            </a>
            <h3>Browse Topics</h3>
          </div>
        </div>

        <div class="topics-page layout__body">
          <form method="GET" action="" class="header__search">
            <label>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>search</title>
                <path
                  d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                ></path>
              </svg>
              <input name = 'i' placeholder="Search for topics" />
            </label>
          </form>
        <div class="topics__scroll">
          <ul class="topics__list">
            <li>
              <a href="{% url 'home' %}" class="active">All <span>{{topics.count}}</span></a>
            </li>
            {% for topic in topics %}
            <li>
              <a href="{% url 'home'%}?i={{topic.name}}" class="active">{{topic.name}} <span>{{topic.room_set.count}}</span></a>
            </li>
            {% endfor %}
          </ul>
        </div>
        </div>
      </div>
    </div>
  </main>

{%endblock%}

base/templates/base/topics_component.html
<div class="topics">
  <div class="topics__header">
    <h2>Browse Topics</h2>
  </div>
  <ul class="topics__list">
    <li>
        <a href="{% url 'home' %}">All <span>{{topics.count}}</span></a>
    </li>
    {% for topic in topics %}
    <li>
        <a href="{% url 'home' %}?i={{topic.name}}">{{topic.name|title}} <span>{{topic.room_set.all.count}}</span></a>
    </li>
    {% endfor %}
  </ul>
  <a class="btn btn--link" href="{% url 'browse-topics' %}">
    More
    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
      <title>chevron-down</title>
      <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
    </svg>
  </a>
</div>  








<!-- <h3>Browse topics</h3>
        <hr>
        <a href="{% url 'home' %}">All</a>
        
        {% for topic in topics %}
            <div>
                <a href="{% url 'home' %}?i={{topic.name}}">{{topic.name}}</a>
            </div>
        {% endfor %} -->